### ISSUE TITLE
Feature request: add logic to prevent elevator/trap creation immediately inside dungeon entrance

### ISSUE THREAD

**Issue by wegotourselvesareader** [primeau/Larn#3]
I had a chuckle this morning when my brand-new, freshly-created character set foot inside the dungeon and was immediately whisked down to level 9 and whacked by a poltergeist.

I appreciate it's random, with long odds against, and it did amuse me. Only last week I was musing to myself about what might happen if an elevator was in the first square the player hits when entering the dungeon...

Would it be possible to add some logic to the code to prevent elevator (both up and down) creation as well as trap creation in the 5 squares immediately adjacent (horizontally, vertically, diagonally) to the dungeon entrance, please? Give the poor medicine-hunting sap *some* chance to survive beyond the first footstep, eh?

I figure no such safety net is needed in the volcano; if the player is competent (or foolish) enough to venture down the volcano then the player can get what's coming.

**Comment by primeau** [comment]
Hey sorry for the late reply, I wasn't getting issue notifications before and missed this...

I hate to disappoint a Larn fan, especially a good-natured one, but I'm going to have to pass on this based on the long odds, and the fact that it doesn't really prevent much "loss" since it only affects brand new characters. I'd be more open to it if there was a chance of harming a character that someone had invested an hour (or even 10 minutes) of time into.
I'd happily take a pull request, but I've gotta bow out of taking this one on. Sorry!
