### ISSUE TITLE
"@" vanishes when using Modern font

### ISSUE THREAD

**Issue by athompso** [primeau/Larn#5]
[playing Beta version, as shown in the screencaps]

DOS font looks fine:
![image](https://user-images.githubusercontent.com/887417/152107259-c65f6691-7b4d-46c5-9587-c5150c5f51fd.png)

but Modern font is missing the "@" character:
![image](https://user-images.githubusercontent.com/887417/152107290-85228c9e-4ed1-43f8-93e9-12cafadf79ff.png)

I don't understand - the only difference is the font???

Using the browser's Inspect function shows that it's just using Courier New:
![image](https://user-images.githubusercontent.com/887417/152107429-58a255e3-38b9-4e11-939e-0fd4474c9b36.png)

However, selecting that character, copying it, and pasting it into anything else gives me a ▓ glyph, not a @, so there really is a problem in the code somewhere.

**Comment by primeau** [comment]
Ahh, yes that's actually intentional although possibly not correct... You can see in player.js:20 and :131 that the @ is only used in the DOS font.

That decision was influenced by the fact that the version I played 30+ years ago used ▓ as the character, and I didn't even know that @ was the 'correct' character until I was adding the DOS font option. I fixed it for that but left the block with the modern font for mostly sentimental reasons.

On the bright side, I've already got a configuration screen on my TODO,txt list with player tile as one of the options. It might take some time, but I will get to it eventually :)
